import './global.css'
import Menu from "@/app/Components/Menu/Menu";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

 return (
    <html   lang="pt">
      <body style={{
          margin : 0,
          padding : 0
      }}>
      <Menu></Menu>
      {children}
      </body>
    </html>
  )
}
